kind: pipeline
type: kubernetes
name: doer-api

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: arm64v8/gradle:5.4-jre8-alpine
    commands:
      - gradle test integrationTest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test

services:
  - name: test-db
    image: postgres:9.6
#    volumes:
#      - name: temp-data
#        path: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: test
#      PG_DATA: /var/lib/postgresql/data/test-db

#volumes:
#  - name: temp-data
#    temp: {}