kind: pipeline
type: kubernetes
name: doer-api

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: arm64v8/gradle:6.6-jdk8
    commands:
      - gradle test integrationTest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test
  - name: "build release candidate"
    image: drone/git
    user: 0
    commands:
      - ./build-release-candidate.sh
  - name: "deploy staging"
    image: pelotech/drone-helm3
    settings:
      add_repos:
        - "chartmuseum=http://chartmuseum-chartmuseum"
        - "bitnami=https://charts.bitnami.com/bitnami"
      mode: upgrade
      chart: doer
      release: doer
      namespace: doer-staging
      values_files:
        - doer-values.yaml
      wait_for_upgrade: true
    environment:
      KUBE_API_SERVER: http://kubernetes.default.svc
      KUBE_TOKEN:
        from_secret: drone-runner-drone-runner-kube-token-zjhnd

services:
  - name: test-db
    image: postgres:9.6
#    volumes:
#      - name: temp-data
#        path: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: test
#      PG_DATA: /var/lib/postgresql/data/test-db

#volumes:
#  - name: temp-data
#    temp: {}