kind: pipeline
type: kubernetes
name: doer-api

platform:
  os: linux
  arch: arm64

clone:
  disable: true

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://$${ACCESS_TOKEN}@github.com/ctailor2/doer-api.git .
      - git checkout $DRONE_COMMIT
    environment:
      ACCESS_TOKEN:
        from_secret: access_token
#  - name: test
#    image: arm64v8/gradle:6.6-jdk8
#    commands:
#      - gradle test integrationTest
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test
  - name: "build release candidate"
    image: drone/git
    commands:
      - git fetch --tags
      - git describe --tags --abbrev=0 --match *-rc > last-version.txt
      - major=$(cut -d . -f 1 last-version.txt)
      - minor=$(cut -d . -f 2 last-version.txt)
      - patch=$(cut -d . -f 3 last-version.txt | cut -d - -f 1)
      - next_patch=$((patch + 1))
      - next_version="$major.$minor.$next_patch-rc"
      - echo "$next_version" | xargs git tag
      - git push --tags
      - 'printf "api:\n\timage:\n\t\ttag: %s\n\n" "$next_version" > doer-values.yaml'
  - name: "deploy staging"
    image: ctailor2/drone-helm3:latest
    settings:
      add_repos:
        - "chartmuseum=http://chartmuseum-chartmuseum"
        - "bitnami=https://charts.bitnami.com/bitnami"
      mode: upgrade
      chart: doer
      release: doer
      namespace: doer-staging
      values_files:
        - doer-values.yaml
      wait_for_upgrade: true
    environment:
      KUBE_API_SERVER: http://kubernetes.default.svc
      KUBE_TOKEN:
        from_secret: drone-runner-drone-runner-kube-token-zjhnd

services:
  - name: test-db
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: test
