version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: doer_api
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432"
  test_db:
    image: postgres
    environment:
      POSTGRES_DB: doer_api_test
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15433:5432"
